######################## default configuration ####################
baseURL = "https://www.hanorepair.de/"
title = "BizCraft - Responsive Html5 Template"
# Default time zone for time stamps; use any valid tz database name: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
timeZone = "Europe/Berlin"
# post pagination
paginate = 6 # see https://gohugo.io/extras/pagination/
# post excerpt
summaryLength = 10 # see https://gohugo.io/content-management/excerpts/
# google analytics
googleAnalytics = "UA-123456-78" # example: UA-123456-78, for more info, read the article https://support.google.com/analytics/answer/1008080?hl=en
# disqus short name
disqusShortname = "themefisher-template" # we use disqus to show comments in blog posts . To install disqus please follow this tutorial https://portfolio.peter-baumgartner.net/2017/09/10/how-to-install-disqus-on-hugo/
# default language
defaultContentLanguage = "de"
# disable language
disableLanguages = [
] # example: ["fr"] for disable french language. see https://gohugo.io/content-management/multilingual/
hasCJKLanguage = false #  If hasCJKLanguage true, auto-detect Chinese/Japanese/Korean Languages in the content. see: https://gohugo.io/getting-started/configuration/#hascjklanguage


############################# Build ##############################
[build]
noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/.*\.(js|ts|jsx|tsx)'
target = '(js|scripts|javascript)'
[[build.cachebusters]]
source = 'assets/.*\.(css|sass|scss)$'
target = '(css|styles|scss|sass)'
[[build.cachebusters]]
source = 'assets/.*\.(.*)$'
target = '$1'


############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS"]

############################# Imaging ##############################
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 90
resampleFilter = "lanczos"

############################# Caches ###############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"

############################# Markup ##############################
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/fontawesome/font-awesome.min.css"
[[params.plugins.css]]
link = "plugins/animate.css"
[[params.plugins.css]]
link = "plugins/prettyPhoto.css"
[[params.plugins.css]]
link = "plugins/owl/owl.carousel.css"
[[params.plugins.css]]
link = "plugins/owl/owl.theme.css"
[[params.plugins.css]]
link = "plugins/flex-slider/flexslider.css"
[[params.plugins.css]]
link = "plugins/cd-hero/cd-hero.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/style-switcher.js"
[[params.plugins.js]]
link = "plugins/owl/owl.carousel.js"
[[params.plugins.js]]
link = "plugins/jquery.prettyPhoto.js"
[[params.plugins.js]]
link = "plugins/flex-slider/jquery.flexslider.js"
[[params.plugins.js]]
link = "plugins/cd-hero/cd-hero.js"
[[params.plugins.js]]
link = "plugins/isotope.js"
[[params.plugins.js]]
link = "plugins/ini.isotope.js"
[[params.plugins.js]]
link = "plugins/wow.min.js"
[[params.plugins.js]]
link = "plugins/jquery.easing.1.3.js"
[[params.plugins.js]]
link = "plugins/jquery.counterup.min.js"
[[params.plugins.js]]
link = "plugins/waypoints.min.js"


############################## English navigation ###############################

[[Languages.de.menu.main]]
weight = 1
name = "Smartphones"
[[Languages.de.menu.main.params]]
hasChildren = true
section = "smartphone-hersteller"

[[Languages.de.menu.main]]
weight = 2
name = "Tablets"
[[Languages.de.menu.main.params]]
hasChildren = true
section = "tablet-hersteller"

[[Languages.de.menu.main]]
weight = 3
name = "Macbook & iMac"
URL = "macbook-und-imac/"

[[Languages.de.menu.main]]
weight = 4
name = "Über uns"
hasChildren = true

[[Languages.de.menu.main]]
parent = "Über uns"
name = "Kontakt"
URL = "kontakt/"

[[Languages.de.menu.main]]
parent = "Über uns"
name = "Anfahrt"
URL = "anfahrt/"

[[Languages.de.menu.main]]
parent = "Über uns"
name = "Standorte"
URL = "standorte/"


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "This is meta description"
author = "HanoRepair"
# contact info
address = "Marienstraße 40a<br>30171 Hannover"
phone = "[0511-34082318](tel:0511-34082318)"
email = "info@hanorepair.de"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# copyright
copyright = "Copyright &copy; by HanoRepair"

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

############################# social site ########################
[[params.social]]
name = "facebook"
icon = "fa-facebook"                          # fontawesome icon pack 4.7 | https://fontawesome.com/v4.7.0/icons/
link = "https://www.facebook.com/hanorepair/"

[[params.social]]
name = "instagram"
icon = "fa-instagram"                          # fontawesome icon pack 4.7 | https://fontawesome.com/v4.7.0/icons/
link = "https://www.instagram.com/hanorepair/"

[[params.social]]
name = "github"
icon = "fa-whatsapp"                                                                                                                         # fontawesome icon pack 4.7 | https://fontawesome.com/v4.7.0/icons/
link = "https://wa.me/4951134082318?text=Hallo!%20Ich%20interessiere%20mich%20f%C3%BCr%20eine%20Smartphone-%20oder%20eine%20Tabletreparatur"

################################### English language #####################################
[Languages.de]
languageName = "De"
languageCode = "de-de"
contentDir = "content/de"
weight = 1

[Languages.de.params]
# footer content
footer_content = "Rufen Sie an oder kommen Sie vorbei.<br>Wir helfen Ihnen gerne weiter."
# copyright
copyright = "Copyright by HanoRepair | Created by [HanovaTech](https://hanovatech.de/)"
